name: Create Release

on:
  # Currently on workflow dispatch manually but we could give other trigger variants later on
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  prerequisite:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.repository.outputs.repository_name }}
      branch: ${{ steps.branch.outputs.branch_name }}
      tag: ${{ steps.tag.outputs.tag_name }}
    steps:
      - id: repository
        run: |
          REPOSITORY_NAME=${{ github.repository }}
          # Extract repository name only (optional)
          echo "repository_name=$REPOSITORY_NAME" >> "$GITHUB_OUTPUT"
      - id: branch
        run: |
          BRANCH_NAME=${{ inputs.branch_name }}
          if [[ -z "$BRANCH_NAME" ]]; then
            # Use development branch if not provided
            BRANCH_NAME="development"
          fi
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
      - id: tag
        run: |
          TAG_NAME=${{ inputs.tag_name }}
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: prerequisite
    steps:
      - name: Echo prerequisites
        run: |
          echo repository: ${{ needs.prerequisite.outputs.repository }}
          echo branch: ${{ needs.prerequisite.outputs.branch }}
          echo tag: ${{ needs.prerequisite.outputs.tag }}
      - name: Create release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: ${{ needs.prerequisite.outputs.repository }}
          tag_name: ${{ needs.prerequisite.outputs.tag }}
          target_commitish: ${{ needs.prerequisite.outputs.branch }}
          body: "Automated release from ${{ needs.prerequisite.outputs.branch }} branch"
          
