name: Create Release

on:
  # Currently on workflow dispatch manually but we could give other trigger variants later on
  workflow_call:
    inputs:
      tag_name:
      description: "Tag name for the release (optional)"
      required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run: |
          REPOSITORY_NAME=${{ github.repository }}
          # Extract repository name only (optional)
          echo "Repository name: $REPOSITORY_NAME"
          
      - name: Get tag names
        run: |
          TAG_NAME=${{ inputs.tag_name }}
          if [[ -z "$TAG_NAME" ]]; then
            # Use latest tag if not provided
            TAG_NAME=$(git describe --tags --abbrev=0)
          fi
          echo "Tag name: $TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_name.outputs.TAG_NAME }}
          target_commitish: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
          release_body: "Automated release from ${{ steps.get_branch_name.outputs.BRANCH_NAME }} branch"
          
