name: Create Release

on:
  # Currently on workflow dispatch manually but we could give other trigger variants later on
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Get repository name
        run: |
          REPOSITORY_NAME=${{ github.repository }}
          # Extract repository name only (optional)
          echo "Repository name: $REPOSITORY_NAME"
          
      - name: Get branch name
        run: |
          BRANCH_NAME=${{ inputs.branch_name }}
          if [[ -z "$BRANCH_NAME" ]]; then
            # Use development branch if not provided
            BRANCH_NAME="development"
          fi
          echo "Branch name: $BRANCH_NAME" >> $GITHUB_OUTPUT
          
      - name: Get tag name
        run: |
          TAG_NAME=${{ inputs.tag_name }}
          echo "Tag name: $TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_name.outputs.TAG_NAME }}
          target_commitish: ${{ steps.get_branch_name.outputs.BRANCH_NAME }}
          release_body: "Automated release from ${{ steps.get_branch_name.outputs.BRANCH_NAME }} branch"
          
