name: Create Release

on:
  # Currently on workflow dispatch manually but we could give other trigger variants later on
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  prerequisite:
    runs-on: ubuntu-latest
    outputs:
      repository_name: ${{ steps.get-inputs.outputs.repository_name }}
      branch_name: ${{ steps.get-inputs.outputs.branch_name }}
      tag_name: ${{ steps.get-inputs.outputs.tag_name }}
    steps:
      - id: get-inputs
        run: |
          REPOSITORY_NAME=${{ github.repository }}
          # Extract repository name only (optional)
          echo "repository_name=$REPOSITORY_NAME" >> "$GITHUB_OUTPUT"
          BRANCH_NAME=${{ inputs.branch_name }}
          if [[ -z "$BRANCH_NAME" ]]; then
            # Use development branch if not provided
            BRANCH_NAME="development"
          fi
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"
          TAG_NAME=${{ inputs.tag_name }}
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: prerequisite
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prerequisite.outputs.tag_name }}
          target_commitish: ${{ needs.prerequisite.outputs.branch_name }}
          release_body: "Automated release from ${{ needs.prerequisite.outputs.branch_name }} branch"
          
