name: Send Email - Tag Created
on:
    workflow_call:
        inputs:
            # email-to:
            #     required: true
            #     type: string
            # email-cc:
            #     required: true
            #     type: string
            tag-version:
                required: true
                type: string
jobs:
    send-email:
        name: Send Email
        runs-on: ubuntu-latest
        steps:
          - name: Sender Name configure
            id: sender-name
            run: |
                if [[ -n "${{ secrets.SENDER_NAME }}" ]]; then
                    echo "SENDER_NAME=${{ secrets.SENDER_NAME }}" >> $GITHUB_ENV
                else
                    REPOSITORY_OWNER_NAME=${{ github.repository_owner }}
                    echo "SENDER_NAME=${REPOSITORY_OWNER_NAME^}" >> $GITHUB_ENV
                fi

## TODO: USE EMAIL TEMPLATES

          - name: 📧 Send mail
            uses: dawidd6/action-send-mail@v3
            with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{ secrets.MAIL_USERNAME }}
                password: ${{ secrets.MAIL_PASSWORD }}
                secure: true
                from: ${{ env.SENDER_NAME }}
                to: ${{ secrets.IDS }}
                cc: ${{ secrets.MAINTAINER_ID }}
                subject: Tag Created - ${{ github.event.repository.name }} v${{ inputs.tag-version }}. 🚀
                html_body: |
                    <html lang="en">

                    <head>
                        <meta charset="UTF-8">
                        <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    </head>

                    <body style="font-size: 1rem;">
                        <p>Hi Maintainers,</p>

                        <p>
                        Tag created ${{ github.event.repository.name }} ${{ inputs.tag-version }}. 🚀<br>
                        You can check out the details by clicking below link
                        https://github.com/wrappid/${{ github.event.repository.name }}/releases/tag/v${{ inputs.tag-version }}
                        </p>
                    
                        <p>Thanks and Regards,<br>
                        ${{ env.SENDER_NAME }}</p>
                        <footer style="font-size: 0.8rem; color: #ccc; height: 30px; line-height: 30px;">Generate by "Create Tag - CI" GitHub Action</footer>
                    </body>

                    </html>

