name: Send Email - Failure
on:
  workflow_call:
    inputs:
      tag-version:
        required: true
        type: string
      EMAIL_SENDER_NAME:      ## Optional
        type: string
    secrets:
      EMAIL_SERVER_ADDRESS:
        required: true
      EMAIL_SERVER_PORT:
        required: true
      EMAIL_USER_ID:
        required: true
      EMAIL_USER_PASSWORD:
        required: true
      EMAIL_TO:
        required: true
      EMAIL_CC:               ## Optional
      EMAIL_BCC:              ## Optional

jobs:
  send-email:
    name: Send Email Failure
    runs-on: ubuntu-latest
    steps:
      - name: Sender Name configure
        id: sender-name
        run: |
          if [[ -n "${{ inputs.EMAIL_SENDER_NAME }}" ]]; then
              echo "SENDER_NAME=${{ inputs.EMAIL_SENDER_NAME }}" >> $GITHUB_ENV
          else
              REPOSITORY_OWNER_NAME=${{ github.repository_owner }}
              echo "SENDER_NAME=${REPOSITORY_OWNER_NAME^}" >> $GITHUB_ENV
          fi

      ## TODO: USE EMAIL TEMPLATES

      - name: 📧 Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER_ADDRESS }}
          server_port: ${{ secrets.EMAIL_SERVER_PORT }}
          username: ${{ secrets.EMAIL_USER_ID }}
          password: ${{ secrets.EMAIL_USER_PASSWORD }}
          secure: true
          from: ${{ env.SENDER_NAME }}
          to: ${{ secrets.EMAIL_CC }}
          subject: ⚠️ FAIL ${{ github.workflow }} - ${{ github.event.repository.name }} ${{ inputs.tag-version }}.
          html_body: |
            <html lang="en">

            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
            </head>

            <body style="font-size: 1rem;">
              <p>Hi Admin,</p>

              <p>
              ${{ github.workflow }} for ${{ github.event.repository.name }} ${{ inputs.tag-version }} has failed <br>
              Check out the details by clicking below link
              https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}
              </p>

              <p>Thanks and Regards,<br>
              ${{ env.SENDER_NAME }}</p>
              <footer style="font-size: 0.8rem; color: #ccc; height: 30px; line-height: 30px;">Generated by "${{ github.workflow }}" GitHub Action. <br>Triggered by ${{ github.actor }}</footer>
            </body>

            </html>

