on:
  workflow_call:
      inputs:
        GIT_USER_NAME:
          required: true
          type: string
        TOOLKIT_VERSION:
          required: true
          type: string
        EMAIL_NOTIFY:
          required: true
          type: string
          default: "true"
        EMAIL_SENDER_NAME:
          required: false
          type: string
      secrets:
        PAT:
          required: true
        GIT_USER_EMAIL:
          required: true
        WRAPPID_REGISTRY_TOKEN:
          required: true
  ## Below secrets are required if EMAIL_NOTIFY is TRUE
        EMAIL_SERVER_ADDRESS:
        EMAIL_SERVER_PORT:
        EMAIL_USER_ID:
        EMAIL_USER_PASSWORD:
        EMAIL_TO:
        EMAIL_CC:     ## Optional
        EMAIL_BCC:    ## Optional

name: Create App Release - CD

jobs:

  check-pre-requisites:
    name: Check Pre-requisites
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      tag-version: ${{ steps.tag.outputs.tag }}
      release-exist: ${{ steps.check_release.outputs.release_exists }}

    steps:
      - name: Check if tag is provided
        id: check_tag
        run: echo ::set-output name=tag_exists::$(if [ -n "${{ github.event.inputs.tag-name }}" ]; then echo "true"; else echo "false"; fi)

      - name: 🛒 Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get Current Tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Print received tag from action
        run: echo ${{ steps.current-tag.outputs.tag }}

      - name: Process Inputs
        id: tag
        run: |
          if [ -n "${{ github.event.inputs.tag-name }}" ]; then
            echo "::set-output name=tag::${{ github.event.inputs.tag-name }}"
          else
            echo "::set-output name=tag::${{ steps.current-tag.outputs.tag }}"
          fi

      - name: Print final tag to checkout
        run: echo ${{ steps.tag.outputs.tag }}


      - name: Check if release exists
        id: check_release
        run: |
          TAG_NAME=${{ steps.tag.outputs.tag }}
          echo $(gh release view $TAG_NAME --json tagName) > tempTagName.json
          RELEASE_EXISTS=$(cat tempTagName.json | jq .tagName)
          if [ -z "$RELEASE_EXISTS" ]; then
            echo "::set-output name=release_exists::no"
          else
            echo "::set-output name=release_exists::yes"
          fi
        env:
          GH_TOKEN: ${{ secrets.PAT }}

# TODO 1: DIFFERENT JOB TO CREATE BUILD AND BUILD ARTIFACT.
# TODO 2: EACH BUILD PARALLEL JOB --> DONE
# TODO 3: OPTION TO SKIP PARTICULAR BUILD

  build-android:
    needs: check-pre-requisites
    name: Build Android
    if: needs.check-pre-requisites.outputs.release-exist == 'no'
    runs-on: ubuntu-latest
    steps:

      - name: 🛒 Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.check-pre-requisites.outputs.tag-version }}
          token: ${{ secrets.PAT }}

      - name: 🛠 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/wrappid
        env:
          NODE_AUTH_TOKEN: ${{secrets.WRAPPID_REGISTRY_TOKEN }} 

      - name: 🛠 Setup gh and git
        run: |
          echo ${{secrets.PAT}} | gh auth login --with-token
          git config user.name "${{ inputs.GIT_USER_NAME}}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Setup Wrappid npm registry
        run: |
          npm config set @wrappid:registry https://npm.pkg.github.com/wrappid
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.WRAPPID_REGISTRY_TOKEN }}

      - name: ⬇️ Setup Project
        run: | 
         echo Installing Node Modules
         npm ci --omit-dev

      - name: Setup Wrappid Toolkit
        run: npm install -g @wrappid/toolkit@${{ inputs.TOOLKIT_VERSION }}

      - name: Check Wrappid Version
        run: wrappid --version

      - name: Wrappid setup mobile
        run: |
          gh auth status
          echo Starting Setup.........................
          wrappid setup mobile --env=stage

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
#           cache-dependency-path: /.wrappid/runtime/mobile/android/

      - name: Change Permission of Gradle
        run: cd .wrappid/runtime/mobile/android/ && chmod +x gradlew

      - name: Build Wrappid android
        run: |
          gh auth status
          echo Starting Build.........................
          wrappid build android

      - name: Print version
        run: echo ${{ needs.check-pre-requisites.outputs.tag-version }}

      - run: ls -l

      - name: Move apk to root
        run: mv build/mobile/android/app-debug.apk android-${{ needs.check-pre-requisites.outputs.tag-version }}.apk

      - run: ls -l

      - name: Get wrappid logs
        run: cp $(npm root -g)/@wrappid/logs/logs.log android-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
            name: android-${{ needs.check-pre-requisites.outputs.tag-version }}
            path: |
              android-${{ needs.check-pre-requisites.outputs.tag-version }}.apk
              android-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log

  build-web:
    needs: check-pre-requisites
    name: Build Web
    if: needs.check-pre-requisites.outputs.release-exist == 'no'
    runs-on: ubuntu-latest
    steps:

      - name: Print Tag Version
        run: echo ${{ needs.check-pre-requisites.outputs.tag-version }}

      - name: 🛒 Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.check-pre-requisites.outputs.tag-version }}
          token: ${{ secrets.PAT }}

      - name: 🛠 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/wrappid
        env:
          NODE_AUTH_TOKEN: ${{secrets.WRAPPID_REGISTRY_TOKEN }} 

      - name: 🛠 Setup gh and git
        run: |
          echo ${{secrets.PAT}} | gh auth login --with-token
          git config user.name "${{ inputs.GIT_USER_NAME}}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Setup Wrappid npm registry
        run: |
          npm config set @wrappid:registry https://npm.pkg.github.com/wrappid
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.WRAPPID_REGISTRY_TOKEN }}

      - name: ⬇️ Setup Project
        run: | 
         echo Installing Node Modules
         npm ci --omit-dev

      - name: Setup Wrappid Toolkit
        run: npm install -g @wrappid/toolkit@${{ inputs.TOOLKIT_VERSION }}

      - name: Check Wrappid Version
        run: wrappid --version

      - name: Wrappid setup web
        run: |
          gh auth status
          echo Starting Setup.........................
          wrappid setup web --env=stage

      - name: Build Wrappid Web
        run: |
          gh auth status
          echo Starting Build.........................
          wrappid build Web

      - name: Zip build
        run: |
          sudo apt install zip -y
          cd build/web
          zip -r web-${{ needs.check-pre-requisites.outputs.tag-version }}.zip *

      - run: ls -l

      - name: Move Web zip to root
        run: mv build/web/web-${{ needs.check-pre-requisites.outputs.tag-version }}.zip web-${{ needs.check-pre-requisites.outputs.tag-version }}.zip

      - name: Get wrappid logs
        run: cp $(npm root -g)/@wrappid/logs/logs.log web-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log

      - run: ls -l

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
            name: web-${{ needs.check-pre-requisites.outputs.tag-version }}
            path: |
              web-${{ needs.check-pre-requisites.outputs.tag-version }}.zip
              web-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log

  create-release:
    needs: [check-pre-requisites, build-web, build-android]
    name: Create Release
    if: needs.check-pre-requisites.outputs.release-exist == 'no'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: 🛒 Checkout Tag
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.check-pre-requisites.outputs.tag-version }}
          token: ${{ secrets.PAT }}

      - name: 🛠 Setup gh and git
        run: |
          echo ${{secrets.PAT}} | gh auth login --with-token
          git config user.name "${{ inputs.GIT_USER_NAME}}"
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Generate Release notes
        run: curl -o- https://raw.githubusercontent.com/wrappid/workflows/main/util-scripts/release_notes.sh | bash -s ${{ github.repository_owner }} ${{ github.event.repository.name }}


      - name: Download Android Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-${{ needs.check-pre-requisites.outputs.tag-version }}

      - name: Download Web Artifact
        uses: actions/download-artifact@v4
        with:
          name: web-${{ needs.check-pre-requisites.outputs.tag-version }}

      - run: ls -al
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}} # Personal Access Token
        with:
          tag_name: ${{ needs.check-pre-requisites.outputs.tag-version }}
          release_name: ${{ needs.check-pre-requisites.outputs.tag-version }}
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false

      - name: Upload Release Asset Web
        id: upload-web-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT}} # Personal Access Token
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./web-${{ needs.check-pre-requisites.outputs.tag-version }}.zip
          asset_name: "web-${{ needs.check-pre-requisites.outputs.tag-version }}.zip"
          asset_content_type: application/zip

      - name: Upload Release Asset Android
        id: upload-android-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./android-${{ needs.check-pre-requisites.outputs.tag-version }}.apk
          asset_name: "android-${{ needs.check-pre-requisites.outputs.tag-version }}.apk"
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset Web Wrappid-Logs
        id: upload-web-log-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./web-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log
          asset_name: "web-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log"
          asset_content_type: text/plain

      - name: Upload Release Asset Android Wrappid-Logs
        id: upload-android-log-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./android-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log
          asset_name: "android-wrappid-logs-${{ needs.check-pre-requisites.outputs.tag-version }}.log"
          asset_content_type: text/plain

  call-send-email-released:
      needs: [create-release, check-pre-requisites]
      if: needs.check-pre-requisites.outputs.release-exist == 'no' && inputs.EMAIL_NOTIFY == 'true'
      permissions: write-all
      uses: wrappid/workflows/.github/workflows/send-email-released.yml@main
      with:
        tag-version: ${{ needs.check-pre-requisites.outputs.tag-version }}
        EMAIL_SENDER_NAME: ${{ inputs.EMAIL_SENDER_NAME }}
      secrets:
        EMAIL_SERVER_ADDRESS: ${{ secrets.EMAIL_SERVER_ADDRESS }}
        EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }}
        EMAIL_USER_ID: ${{ secrets.EMAIL_USER_ID }}
        EMAIL_USER_PASSWORD: ${{ secrets.EMAIL_USER_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_CC: ${{ secrets.EMAIL_CC }}       ## Optional
        EMAIL_BCC: ${{ secrets.EMAIL_BCC }}     ## Optional
