name: Create Tag - CI

on:
  workflow_call:

jobs:        
    create-tag:
      name: Create Tag
      runs-on: ubuntu-latest
      permissions: write-all
      outputs:
        tag-version:  ${{ steps.extract_version.outputs.version }}
      steps:
  
        - name: 🛠 Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 16
            registry-url: https://npm.pkg.github.com/wrappid
          env:
            NODE_AUTH_TOKEN: ${{secrets.WRAPPID_REGISTRY_TOKEN}}      
          
        - name: 🛒 Checkout repository
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.PAT }}
  
        - name: 🛠 Setup gh and git
          run: |
            # echo ${{secrets.PAT}} | gh auth login --with-token
            git config user.name "${{ secrets.GHUSER_NAME }}"
            git config user.email "${{ secrets.GHUSER_EMAIL }}"
  
        - name: 👀 Process Inputs
          id: release-type-input
          run: |
            case "${{ github.event.inputs.version_type }}" in
              " -r patch" | " -r major" | " -r minor" )
                VERSION_TYPE_DEFAULT="${{ github.event.inputs.version_type }}"
                ;;
              * )
                if [ -n "${{ secrets.VERSION_TYPE_REPOSITORY_DEFAULT }}" ]; then
                  VERSION_TYPE_DEFAULT="${{ secrets.VERSION_TYPE_REPOSITORY_DEFAULT }}"
                else
                  VERSION_TYPE_DEFAULT=" -r patch"
                fi
                ;;
            esac
            ## SAFETY CHECK
            if [ -z "$VERSION_TYPE_DEFAULT" ]; then
              VERSION_TYPE_DEFAULT=" -r patch"
            fi

            echo "Version type: $VERSION_TYPE_DEFAULT"
            echo "::set-output name=version_type::$VERSION_TYPE_DEFAULT"


        - name: ⬇️ Setup Project
          run: | 
           echo Installing Node Modules
           npm ci
  
## TODO: 
##       ADD ATTRIBUTION TRIGGER
##       CHECK IF ANY CHANGES IN ATTRIBUTION
##       IF CHANGES FOUND, COMMIT

# - name: 🔄 Update Attribution
        #   run: |
        #    npm run attributions:gen
        #    chmod +x $ATTRIBUTION_SCRIPT_PATH
        #    bash $ATTRIBUTION_SCRIPT_PATH ${{ github.event.repository.name }}
        #    git pull
        #    git add ATTRIBUTIONS.md
        #    git commit -m "docs(global): :memo: update attribution
  
        #    update attributions content
  
        #    by Publish CI"
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.PAT }}
  
        - name: ⬆️ Update version
          run:  npm run release -- ${{ steps.release-type-input.outputs.version_type}}
  
  
        - name: 🚀 Update remote repository
          run: git push --follow-tags origin development

          
        - name: Extract version
          id: extract_version
          uses: Saionaro/extract-package-version@v1.0.6
    
        - name: Print version
          run: echo ${{ steps.extract_version.outputs.version }}


    print-version:
        runs-on: ubuntu-latest
        needs: create-tag
        permissions: write-all
        steps:
            - name: print
              run: echo ${{ needs.create-tag.outputs.tag-version }}
  
    call-send-email-tag-created:
          needs: create-tag
          permissions: write-all
          uses: wrappid/workflows/.github/workflows/send-email-tag-created.yml@main
          secrets: inherit
          with:
            tag-version: ${{ needs.create-tag.outputs.tag-version }}
            
  
      
  
