name: App Deploy - CD

on:
  workflow_call:
    inputs:
      EMAIL_NOTIFY:
        required: true
        type: string
        default: "true"
      EMAIL_SENDER_NAME:
        required: false
        type: string
    secrets:
      PAT:
        required: true
      REMOTE_HOST:
         required: true
      REMOTE_SSH_KEY:
         required: true
      REMOTE_SSH_USER:
         required: true
## Below secrets are required if EMAIL_NOTIFY is TRUE
      EMAIL_SERVER_ADDRESS:
      EMAIL_SERVER_PORT:
      EMAIL_USER_ID:
      EMAIL_USER_PASSWORD:
      EMAIL_TO:
      EMAIL_CC:     ## Optional
      EMAIL_BCC:    ## Optional

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    name: App Deploy
    outputs:
      tag-version: ${{ steps.current-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get Current Tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Print received tag from action
        run: echo ${{ steps.current-tag.outputs.tag }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}       
          username: ${{ secrets.REMOTE_SSH_USER }}     
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script: |
            sudo -u ec2-user curl -o- https://raw.githubusercontent.com/wrappid/workflows/main/deploy-scripts/app-deploy.sh | bash -s ${{ github.repository_owner }} ${{ github.event.repository.name }}

  call-send-email-deployed:
      needs: app-deploy
      if: ${{ inputs.EMAIL_NOTIFY }} == true
      permissions: write-all
      uses: wrappid/workflows/.github/workflows/send-email-deploy.yml@main
      secrets:
        EMAIL_SERVER_ADDRESS: ${{ secrets.EMAIL_SERVER_ADDRESS }}
        EMAIL_SERVER_PORT: ${{ secrets.EMAIL_SERVER_PORT }}
        EMAIL_USER_ID: ${{ secrets.EMAIL_USER_ID }}
        EMAIL_USER_PASSWORD: ${{ secrets.EMAIL_USER_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_CC: ${{ secrets.EMAIL_CC }}       ## Optional
        EMAIL_BCC: ${{ secrets.EMAIL_BCC }}     ## Optional
      with:
        tag-version: ${{ needs.app-deploy.outputs.tag-version }}
        EMAIL_SENDER_NAME: ${{ inputs.EMAIL_SENDER_NAME }}
