name: App Deploy - CD

on:
  workflow_call:

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    name: App Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.PAT }}

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_STAGE_HOST }}       
          username: ${{ secrets.AWS_STAGE_USER }}     
          key: ${{ secrets.AWS_STAGE_SSH_KEY }}
          port: 22
          script: |
            sudo -u ec2-user curl -o- https://raw.githubusercontent.com/wrappid/workflows/main/deploy-scripts/app-deploy.sh | bash -s ${{ github.event.repository.name }}
  
  notify:
    needs: app-deploy
    runs-on: ubuntu-latest
    name: Notify through email
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Get Current Tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Print received tag from action
        run: echo ${{ steps.current-tag.outputs.tag }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.MAIL_USERNAME}}
            password: ${{secrets.MAIL_PASSWORD}}
            secure: true
            from: Wrappid Care
            to: ${{secrets.IDS}}
            cc: ${{secrets.MAINTAINER_ID}}
            subject: Deployed - Test Wrappid App - ${{ steps.current-tag.outputs.tag }}. 🚀
            html_body: |
              <html lang="en">

              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Exciting News from Wrappiders</title>
              </head>

              <body>
                <p>Hi Wrappider Testers 🕵🏽‍♂️,</p>

                <p>Its time to hunt those bugs again 🐛<br>
                  We have deployed a new version of our test-wrappid-app, ${{ steps.current-tag.outputs.tag }}. 🚀<br>
                  Start your hunt ${{ secrets.TEST_APP_URL }}<br>
                  This version comes with some amazing new features and improvements that will make your experience even better.
                  You can check out the latest release details here https://github.com/wrappid/test-wrappid-app/releases/latest.
                </p>

                <p>Thanks and Regards,<br>
                  Wrappid Care<br>
                  (Generated by the deploy GitHub Action workflow)</p>
              </body>

              </html>
            ignore_cert: true
            convert_markdown: true
            # attachments: attachments.zip,git.diff
            priority: normal