name: Service Deploy - CD

on:
  workflow_call:

jobs:
  service-deploy:
    runs-on: ubuntu-latest
    name: Serivce Deploy
    outputs:
      tag-version: ${{ steps.current-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.PAT }}

      - name: Get Current Tag
        id: current-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Print received tag from action
        run: echo ${{ steps.current-tag.outputs.tag }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_STAGE_HOST }}       
          username: ${{ secrets.AWS_STAGE_USER }}     
          key: ${{ secrets.AWS_STAGE_SSH_KEY }}
          port: 22
          script: |
            curl -o- https://raw.githubusercontent.com/wrappid/workflows/main/deploy-scripts/service-deploy.sh | bash -s ${{ github.event.repository.name }}


  call-send-email-deployed:
      needs: service-deploy
      permissions: write-all
      uses: wrappid/workflows/.github/workflows/send-email-deploy.yml@main
      secrets: inherit
      with:
        tag-version: ${{ needs.service-deploy.outputs.tag-version }}